// Aurora Session Configuration
// This file is auto-generated by Terraform or can be manually edited

export const CONFIG = {
    // WebSocket endpoint URL for API Gateway
    // Format: wss://[api-id].execute-api.[region].amazonaws.com/[stage]
    websocket_url: "wss://kbv73t4jhj.execute-api.eu-north-1.amazonaws.com/production",
    
    // Idle session timeout in minutes (default: 15)
    // Session will auto-terminate after this period of inactivity
    // Warning appears before timeout (see idle_warning_minutes below)
    idle_timeout_minutes: 15,
    
    // Warning time before idle timeout in minutes (default: 2)
    // Alert will appear this many minutes before session terminates
    idle_warning_minutes: 2,
    
    // Optional: Add other configuration as needed
    region: "eu-north-1",
    environment: "prod"
};
