// Aurora Session Configuration
// This file is auto-generated by Terraform or can be manually edited

export const CONFIG = {
    // WebSocket endpoint URL for API Gateway
    // Format: wss://[api-id].execute-api.[region].amazonaws.com/[stage]
    websocket_url: "wss://kbv73t4jhj.execute-api.eu-north-1.amazonaws.com/production",
    
    // Idle session timeout in minutes (default: 15)
    //
    // NOTE: not enforced yet. The value is passed to the session instance,
    // but nothing there tracks activity, so no session is terminated for
    // being idle. A session ends when the browser disconnects (closing the
    // tab, or losing the connection) or when you terminate it from the menu.
    idle_timeout_minutes: 15,

    // Warning time before idle timeout in minutes (default: 2)
    // Unused until the idle timeout above is implemented.
    idle_warning_minutes: 2,
    
    // Optional: Add other configuration as needed
    region: "eu-north-1",
    environment: "prod"
};
